#Configuration file for core log4j

#Specify the priority level to set and the type of Appender (i.e. the type of log output file) for the root category
log4j.rootCategory=ERROR, D

#Use the daily rolling file appender mechanism, i.e. the file will change over to a new file every day
log4j.appender.D=org.apache.log4j.DailyRollingFileAppender

#Specify {path} - the name of the file (fully qualified with path) where the log messages will be saved. 

log4j.appender.D.File=C:/IMS_LOG/ims_log.log
# Specify that the file should roll over every day at midnight 
log4j.appender.D.DatePattern = '.'yyyy-MM-dd

log4j.appender.D.layout=org.apache.log4j.PatternLayout

#Use a conversion pattern 
#log4j.appender.D.layout.ConversionPattern = %d | %5p | [%t] | %c:%M | %m %n
#log4j.appender.D.layout.ConversionPattern = %m %n
log4j.appender.D.layout.ConversionPattern =  %d| %m %n